<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260402064415 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE blog
                (
                    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    title VARCHAR(255) NOT NULL,
                    text TEXT NOT NULL,
                    description VARCHAR(255) NOT NULL,
                    PRIMARY KEY (id)
                )
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE blog');
    }
}
