<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260403073321 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE tags_blogs (blog_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (blog_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_9F7F3C28DAE07E97 ON tags_blogs (blog_id)');
        $this->addSql('CREATE INDEX IDX_9F7F3C28BAD26311 ON tags_blogs (tag_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE tags_blogs ADD CONSTRAINT FK_9F7F3C28DAE07E97 FOREIGN KEY (blog_id) REFERENCES blog (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tags_blogs ADD CONSTRAINT FK_9F7F3C28BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE tags_blogs DROP CONSTRAINT FK_9F7F3C28DAE07E97');
        $this->addSql('ALTER TABLE tags_blogs DROP CONSTRAINT FK_9F7F3C28BAD26311');
        $this->addSql('DROP TABLE tags_blogs');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
